### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by ImTheCodeFarmer**
This pull request moves the server ID to the ENV. We have removed many unneeded commented code. 

Additionally, this includes finalized scoped features that are ready for testing.

### CODE REVIEW

**Comment by wileyj** [comment]
> This pull request moves the server ID to the ENV. We have removed many unneeded commented code.
> 
> Additionally, this includes finalized scoped features that are ready for testing.

@jhammond2012

can you add a `.gitignore` file to remove some extra files here? files like `.DS_Store`
You'll also need to sign the CLA here: https://cla-assistant.io/blockstack/discord-automod?pullRequest=1  before we can merge. 


An example gitignore we use for other js repos:
```
# OS or Editor folders
.DS_Store
node_modules

# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
.vercel
/.next/
/out/
/build/

# production
/build

# misc
.env*
.idea

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

.now
.mdx-data
.cache
.yalc
yalc.lock
.cache
```

**Comment by wileyj** [comment]
Otherwise, seems fine - once you address those 2 asks we'll get it merged and look into building/deploying

**Comment by ImTheCodeFarmer** [comment]
@wileyj I somehow missed this. I need to get my notifications sorted here. I will fix this first thing tomorrow.

**Comment by ImTheCodeFarmer** [comment]
@wileyj 
image
I try to sign and get success but it still says not signed.

**Comment by wileyj** [comment]
> @wileyj
> image
> I try to sign and get success but it still says not signed.

Very odd, I've never seen this personally but I"m asking around. maybe try using the link in this comment?
If you click the yellow/black icon it'll bring you to the page to "sign" it. 
https://github.com/blockstack/discord-automod/pull/1#issuecomment-716644450

Screenshot 2020-11-02 at 10 19 47

**Comment by wileyj** [comment]
Found the issue. 
Most of the commits you've added are not using a github username, but a local device acccount. 
https://github.com/jhammond2012/discord-automod/commits/improvements

i.e. (name/account removed here), but if you look at this specific commit you'll see your local device account. 
```
commit 704a549df34cf1590987f733e884358d23088030
Date:   Mon Nov 2 09:07:38 2020 -0500

    added git ignore
```

**Pull request closed without merging**
